<?php

namespace App\Http\Middleware;

use App\Facades\SetLoginRouteToGuardFacade;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    protected array $guards;
    protected function unauthenticated($request, array $guards)
    {
        $this->guards = $guards ;
        foreach ($guards as $guard)
            SetLoginRouteToGuardFacade::set($guard);
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            $loginRoute = $this->auth->guard($this->guards[0]);
            return route($loginRoute->routes['login']);
        }
    }
}
